[project]
name = "bonddia-mastodon"
version = "0.1.0"
description = "Mastodon bot for bond diagrams"
requires-python = ">=3.8"
dependencies = [
    "requests",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]
